-- AUTO-GENERATED by tools/gen_manifest.py — do not hand-edit.
-- Regenerate with: python3 tools/gen_manifest.py
return {
  { name = 'ailo-updater', folder = 'ailo-updater', version = '4', file = 'dist/ailo-updater.mpackage' },
  { name = 'Elemental Bonds', folder = 'elemental-bonds', version = '2.9', file = 'dist/elemental-bonds.mpackage' },
  { name = 'IceSafeZone', folder = 'icesafe-zone', version = '1.1', file = 'dist/icesafe-zone.mpackage' },
  { name = 'Icesus Inventory', folder = 'icesus-inventory', version = '9.33', file = 'dist/icesus-inventory.mpackage' },
  { name = 'Icesus Spell Aliases', folder = 'icesus-spell-aliases', version = '1.0', file = 'dist/icesus-spell-aliases.mpackage' },
  { name = 'Lantern Refill', folder = 'lantern-refill', version = '1.0', file = 'dist/lantern-refill.mpackage' },
  { name = 'Mapper Addon', folder = 'mapper-addon', version = '1', file = 'dist/mapper-addon.mpackage' },
  { name = 'Momentum Keybutton', folder = 'momentum-keybutton', version = '1', file = 'dist/momentum-keybutton.mpackage' },
  { name = 'Movement Keybinds', folder = 'movement-keybinds', version = '2', file = 'dist/movement-keybinds.mpackage' },
  { name = 'Party Info', folder = 'party-info', version = '2.3', file = 'dist/party-info.mpackage' },
  { name = 'skill-loop', folder = 'skill-loop', version = '2', file = 'dist/skill-loop.mpackage' },
}
